### ISSUE TITLE
Not quite working? (Windows 10)

### ISSUE THREAD

**Issue by ItsCubeTime** [yes1am/simple-explorer#1]
Hi, so the extension loads fine, I get the simple explorer panel as well as the RMB menu Simple explorer add/remove options for the regular file explorer.

However after creating the simple-explorer.json, adding some directories, restarting vs code (twice) it still wont display anything!

Any help appreciated <3 Ive been wishing for an extension for this for like a redicolously long time, Im glad this exists.

![image](https://user-images.githubusercontent.com/20190653/115413538-8d066c80-a1f5-11eb-830c-3ade66a75198.png)

**Comment by yes1am** [comment]
Thanks @ItsCubeTime ,

I found two problems under Windows:
1. The path format under Windows (such as D:/xxx/xxx ) is not the same as the MacOS path format(such as /User/xxx/xxx), This leads to the problem, and Now I have fixed this problem.  
2. If you right-click on the added path, it seems to be different from the path that should really be added. It works fine when I debug locally, but once I publish to the marketplace, it seems to have problems. For example, **right-clicking**  and add  `/D:/FrontEnd/dom-align` to the simple-explorer.json, but the path that should really be added is `/d:/FrontEnd/dom-align`, There is a problem with case.

If the second problem occurs on your end as well, you can manually modify simple-explorer.json and reload the extension.

I also added some console.log for debug. In VSCode, click `Help` => `Toggle Developer Tools` and you can see the relevant logs.

such as:
![image](https://user-images.githubusercontent.com/25051945/116089635-a6b42200-a6d5-11eb-83c7-5f75f5d2ccbf.png)

the log means, the config is `/Users/songjp/fe/mime/learn-lerna/node_modules/babel-core`,The file that is currently being looped is `/Users/songjp/fe/mime/learn-lerna/package.json`, so `/Users/songjp/fe/mime/learn-lerna/package.json` wont be shown.

I hope this plugin helps you, and feel free to communicate again if you have any questions. I'm looking for a job, so I'm busy preparing for interviews these days, and I'll try to optimize this plugin once my job is stable.

The latest version is 0.0.7, you can try it now.

**Comment by ItsCubeTime** [comment]
Hi  @yes1am and thanks for the effort! Yes indeed the fix is working on my end as well.

![image](https://user-images.githubusercontent.com/20190653/116111810-4910dd00-a6b7-11eb-8050-d45aa90e49dc.png)

I will close this as resolved.
